### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Rentier** [juditacs/wikt2dict#3]
Is http://nessie.nytud.hu/dict down? It looks offline for me at least.

**Comment by juditacs** [comment]
Unfortunately the site (and the DNS) is no longer available. I would upload the dictionaries somewhere, but they are from a really old crawl and it would make more sense to rerun them again.

Are you interested in a particular language pair?

**Comment by Rentier** [comment]
I generated them by myself, it was really easy due to your nice work. Thank you for this project and your quick reply!
